---
- hosts: localhost
  tasks:
    - name: Creation new instance ec2 with ansible
      ec2_instance:
        key_name: default_ec2
        instance_type: t2.micro
        image_id: ami-0dfcb1ef8550277af
        region: us-east-1
        count: 1
        # exact_count: 2
        # count_tag:
        #   type: http
        vpc_subnet_id: subnet-0ef0d5508555e7946
        network:
          assign_public_ip: true
        security_group: http_server_sg
        tags:
          type: http
          Environent: QA
        wait: true
      register: ec2_output
    - debug: var=ec2_output
